---
- name: Copy python and notebooks to volume_2 directory
  block:
    - name: Get homedir
      register: homedir
      find:
        paths: ['/home']
        file_type: directory

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: "{{item['path']}}/data/volume_2/patent_project/"
        state: directory
        mode: '0777'
      with_items: "{{ homedir['files'] }}"

    - name: Create a directory for notebook files if it does not exist
      ansible.builtin.file:
        path: "{{item['path']}}/data/volume_2/patent_project/example/"
        state: directory
        mode: '0777'
      with_items: "{{ homedir['files'] }}"

    - name: Create a directory for python files if it does not exist
      ansible.builtin.file:
        path: "{{item['path']}}/data/volume_2/patent_project/scripts/"
        state: directory
        mode: '0777'
      with_items: "{{ homedir['files'] }}"

    - name: Download create_novelty_impact.py
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/UtrechtUniversity/patent-breakthrough/main/scripts/create_novelty_impact.py"
        dest: "{{item['path']}}/data/volume_2/patent_project/scripts/create_novelty_impact.py"
        mode: '660'
      with_items: "{{ homedir['files'] }}"

    

        
      
